COP 3279: Image comparison table threshold
UKHomeOffice/ide-controller pull request #121
Opened 2020-10-22 22:07 UTC by JimmySunDance

## Description
This branch updates the image comparison table tags with the new score thresholds, configurable in the score config file. 

## To test
- pull branch and run the command `npm ci && npm run build`
- deploy build to dev device
- scan a series of documents that return various "No Data", "Pass" and "Failure" results
- tag should display with appropriate colour, found on the IDE prototype. 

## Developer Checklist

\* Required

- [ ] Up-to-date with master branch? \*

- [ ] Does it have tests?

- [ ] Pull request URL linked to JIRA ticket? \*

- [ ] All reviewer comments resolved/answered? \*

2020-10-23 07:28 UTC, p3dr0migue1 commented on packages/react/src/Components/Molecules/ImageComparisonsTable.jsx
> +    return 0;
Totally valid code, but you could have done it in one line too, just like you did on line 12 (above)

2020-10-26 12:46 UTC, JimmySunDance commented on packages/react/src/Components/Molecules/ImageComparisonsTable.jsx
> +    return 0;
Refactored

2020-10-26 13:31 UTC, Ali-Baker approved these changes

2020-10-26 13:32 UTC, Ali-Baker requested changes

2020-10-26 13:32 UTC, Ali-Baker commented on packages/react/src/Components/Molecules/ImageComparisonsTable.jsx
> +  if (percent < 45 && percent > 0) return 'FAIL';
Actually @JimmySunDance this is now not based on a percentage

2020-10-26 13:55 UTC, Ali-Baker approved these changes

2020-10-26 13:56 UTC, merged