COP-3682 Rotate Camera
UKHomeOffice/ide-controller pull request #150
Opened 2020-11-22 19:44 UTC by Ali-Baker

## Description

## Developer Checklist

\* Required

- [ ] Up-to-date with master branch? \*

- [ ] Does it have tests?

- [ ] Pull request URL linked to JIRA ticket? \*

- [ ] All reviewer comments resolved/answered? \*

2020-11-30 17:12 UTC, rjweeks approved these changes

2020-12-02 16:42 UTC, rjweeks requested changes
Check if there is image distortion.

2020-12-03 13:07 UTC, JimmySunDance approved these changes

2020-12-03 15:15 UTC, JimmySunDance requested changes
Red box is not tracking faces.

2020-12-07 18:00 UTC, rjweeks approved these changes

2020-12-07 19:55 UTC, JimmySunDance approved these changes

2020-12-07 20:05 UTC, merged