COP-1955 Tab Component
UKHomeOffice/ide-controller pull request #24
Opened 2020-09-10 11:08 UTC by JimmySunDance

2020-09-10 15:18 UTC, Ali-Baker commented on packages/react/src/Components/Header.jsx
> -    <StyledHeader
You can remove `StyledHeader` 👆 L5

2020-09-10 15:19 UTC, Ali-Baker commented on packages/react/src/Components/Header.jsx
> +              <svg aria-hidden="true" focusable="false" className="govuk-header__logotype-crown" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 132 97" height="30" width="36">
Maybe we can save the svg as seperate file?

2020-09-10 15:24 UTC, Ali-Baker commented
Looks good so far James. 👏

2020-09-10 21:53 UTC, JimmySunDance commented on packages/react/src/Components/Header.jsx
> +              <svg aria-hidden="true" focusable="false" className="govuk-header__logotype-crown" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 132 97" height="30" width="36">
Image removed as per design prototype.

2020-09-11 07:36 UTC, Ali-Baker commented
You can now rebase for the tests to pass.

2020-09-15 07:43 UTC, Ali-Baker commented on packages/react/package.json
> +    "styled-components": "^5.2.0"
We don't need this package anymore

```suggestion
    "react-scripts": "^3.4.3"
```

2020-09-15 07:45 UTC, Ali-Baker requested changes
Need rebase

2020-09-15 07:47 UTC, Ali-Baker commented on packages/react/src/index.jsx
> +document.body.className = document.body.className
I think it might be useful to add comment to explain why we need this.

2020-09-15 07:48 UTC, Ali-Baker commented on packages/react/src/App.jsx
> -      <Footer />
Are we getting rid of the Footer? if so maybe we cal remove Footer.jsx

2020-09-15 07:49 UTC, Ali-Baker commented on packages/react/src/Components/PageBody.jsx
> +      <main className="govuk-main-wrapper govuk-main-wrapper--auto-spacing" id="main-content" role="main">
I don't think we nee id?

2020-09-15 07:51 UTC, Ali-Baker commented on packages/react/src/Components/MRZTable.jsx
> +// Global imports
👏

2020-09-15 08:00 UTC, Ali-Baker commented on packages/react/src/Components/MRZPanel.jsx
> +        className={ displayTab }
```suggestion
        className={`
          govuk-tabs__panel
          ${isActive ? 'govuk-tabs__panel--hidden' : ''}
        `}
```

2020-09-15 08:01 UTC, Ali-Baker commented on packages/react/src/Components/MRZPanel.jsx
> +  let displayTab = isActive ? "govuk-tabs__panel" : "govuk-tabs__panel govuk-tabs__panel--hidden";
```suggestion

```

2020-09-15 08:01 UTC, Ali-Baker commented on packages/react/src/Components/MRZPanel.jsx
> +        id="mrz-data"
```suggestion

```

2020-09-15 08:02 UTC, Ali-Baker commented on packages/react/src/Components/LiveImage.jsx
> -          style={{ borderRadius: '10px 10px 0 0' }}
```suggestion

```

2020-09-15 08:15 UTC, Ali-Baker commented on packages/react/src/Components/InfoTabs.jsx
> +  const [stateTab, setStateTab] = useState({
```suggestion
  const [active, setActive] = useState({
```

2020-09-15 08:19 UTC, Ali-Baker commented on packages/react/src/Components/InfoTabs.jsx
> +          className={ clickedTab(stateTab.imagePanel) }
This 👇 or something similar might be cleaner.

```suggestion
          className={`
            govuk-tabs__list-item 
            ${ active.imagePanel ? 'govuk-tabs__list-item--selected' : ''}
          `}
```

2020-09-15 08:20 UTC, Ali-Baker commented on packages/react/src/Components/InfoTabs.jsx
> +          className={ clickedTab(stateTab.MRZPanel) }
Same here look at 👆. You could do something similar.

2020-09-15 08:26 UTC, Ali-Baker commented on packages/react/src/Components/ImagePanel.jsx
> +      className={ displayTab }
You could use `tabs__panel ${isActive} ? '' : 'govuk-tabs__panel--hidden'`

2020-09-15 08:26 UTC, Ali-Baker commented on packages/react/src/Components/ImagePanel.jsx
> +      id="image-data"
```suggestion

```

2020-09-15 08:29 UTC, Ali-Baker requested changes

2020-09-15 08:29 UTC, Ali-Baker commented on packages/react/src/Components/PhotoColumn.jsx
> +    <div class="govuk-tabs" data-module="govuk-tabs">
```suggestion
<div className="govuk-tabs" data-module="govuk-tabs">
```

2020-09-15 08:30 UTC, Ali-Baker commented
Well done 👏  James. This is a big piece of work. Let's try to finish it before the end of the sprint.

2020-09-15 08:57 UTC, JimmySunDance commented on packages/react/src/App.jsx
> -      <Footer />
Footer is being removed

2020-09-15 08:59 UTC, JimmySunDance commented on packages/react/src/Components/MRZPanel.jsx
> +  let displayTab = isActive ? "govuk-tabs__panel" : "govuk-tabs__panel govuk-tabs__panel--hidden";
changes made

2020-09-15 14:10 UTC, closed without merging

2020-09-15 14:11 UTC, Ali-Baker commented
https://github.com/UKHomeOffice/ide-controller/pull/33